account_id = "55cb4036f82767a7f0f757a02a1ec8fd"
compatibility_date = "2022-09-06"
compatibility_flags = []
name = "vite-bridge"
route = ''
site = {bucket = "./build", entry-point = "workers-site"}
type = "webpack"
usage_model = ''
workers_dev = true

[env.buidl]
zone_id = 'f88e2f1d3639975a214cd2a56eefba13'
